//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialConsultas
    {
        public int Id { get; set; }
        public int ConsultaId { get; set; }
        public int HiloHostorial { get; set; }
    
        public virtual Consultas Consultas { get; set; }
    }
}
